### PR TITLE
WIP: use modern JavaScript (ES5+) and modern JavaScript build tools

### PR DESCRIPTION
**Pull request by timashev**
@mivion I started this work some time ago, and done all the code & tools migrations internally (inside the module). The only things left are:
- expose (`export`) all module methods properly
- update demo to use updated module exports

What do you think? Should I finish this work? Would you merge this pull request when it is finished?

### CODE REVIEW

**Comment by mivion** [comment]
Hi, thanks for your work.
Please fill free to contribute to this project.
A can add you as contributor, ok?

**Comment by timashev** [comment]
@mivion Yes, sure, add me as a contributor.

**Comment by mivion** [comment]
@timashev welcome! :)

**Comment by 0xStarcat** [comment]
Any reason this wasn't merged? 

Sidenote: I started a similar project: https://github.com/0xStarcat/Moshier-Ephemeris-JS

**Comment by timashev** [comment]
@0xStarcat The only reason is that I had no time yet to do what I mentioned in the [initial comment](https://github.com/mivion/ephemeris/pull/19#issue-293304137), i.e.:
- expose (`export`) all module methods properly
- update demo to use updated module exports

So if you have time to finish this work, it would be great, and yes, please integrate your tests and other refactors into this branch.

**Comment by 0xStarcat** [comment]
that'd be fantastic. sit tight and I'll see what I can do

**Comment by 0xStarcat** [comment]
I've decided to open up my own PR https://github.com/mivion/ephemeris/pull/22 

My fork is a little further along with some refactors. It has complete test coverage of all the body calculations, no issues with azimuth calculations (I tried to debug your branch a bit, but these original calculations are so opaque I decided to give up), and it has a couple other goodies. 

It's not as complete with the ES6 syntax updates as yours is, so maybe we can add those into mine down the road. I instead chose to focus on creating ES6 classes, modules, and implement a few object oriented programming patterns. I figured the syntactical updates can come later because there is some major refactoring needed in this code, which should be easier now with the complete test coverage and new usage classes. 

Hope you can have a look if you find the time and let me know what you think.

Thanks!

**Comment by mivion** [comment]
There conflicts.

**Pull request closed without merging**
